---
title: "Appendix for comment on Nianogo et al."
author: "Michael D Garber"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
---
```{r "setup", include=FALSE, eval=TRUE, echo=FALSE}
library(mapview)
library(tidyverse)
library(here)

#Load data
setwd(here("data","data-processed"))
load("black_complete_geo.RData")
load("hispanic_complete_geo.RData")
```
# Medicaid expansion by state, 2019, available CVD outcome data
## Hispanic CVD data not missing in CDC wonder


```{r}
hispanic_complete_geo %>% 
  filter(year==2019) %>% 
  mutate(treated_char=as.character(treated)) %>% 
  mapview(zcol="treated_char",
          layer.name="Medicaid expansion state, 2019")
```

## Black CVD data not missing in CDC Wonder
```{r}
black_complete_geo %>% 
  filter(year==2019) %>% 
  mutate(treated_char=as.character(treated)) %>% 
  mapview(zcol="treated_char",
          layer.name="Medicaid expansion state, 2019")
```

# Replicate Nianogo et al., Table 1, main text
```{r, eval=T, echo=F,warning=FALSE, message=F}
#Plot following their code
#Not sure how/why it's printing when I'm simly defining the object, but asi es
#plot_est_overall_authors=
setwd(here("data","data-processed"))
load("est_overall_authors.RData")
library(gsynth)
library(panelView)

plot(
  est_overall_authors, 
  type = "counterfactual", 
  raw = "none")

```

